!PARAMETERS

arrivals:
  Q1: 45.0

queues:
  Q1:
    servers: 1
    capacity: 5
    minArrival: 2.0  # Tempo mínimo de chegada
    maxArrival: 4.0  # Tempo máximo de chegada
    minService: 1.0  # Tempo mínimo de serviço
    maxService: 2.0  # Tempo máximo de serviço
  Q2:
    servers: 2
    capacity: 5
    minService: 4.0  # Tempo mínimo de serviço
    maxService: 8.0  # Tempo máximo de serviço
  Q3:
    servers: 2
    capacity: 10
    minService: 5.0  # Tempo mínimo de serviço
    maxService: 15.0  # Tempo máximo de serviço

network:
  - source: Q1
    target: Q2
    probability: 0.80  # Probabilidade de ir de Q1 para Q2
  - source: Q1
    target: Q3
    probability: 0.20  # Probabilidade de ir de Q1 para Q3

rndnumbers:
  - 0.2176
  - 0.0103
  - 0.1109
  - 0.3456
  - 0.9910
  - 0.2323
  - 0.9211
  - 0.0322
  - 0.1211
  - 0.5131
  - 0.7208
  - 0.9172
  - 0.9922
  - 0.8324
  - 0.5011
  - 0.2931

rndnumbersPerSeed: 100000  # Número de aleatórios gerados por semente
seeds:
  - 1
  - 2
  - 3
  - 4
  - 5
